config/routes.rb
Rails.application.routes.draw do
  root 'qualification#index'

  get 'qualification/index' => 'qualification#index'
  get 'qualification/:id/subjects' => 'qualification#subjects', as: :subjects

end

app/models/asset.rb
# == Schema Information
#
# Table name: assets
#
#  id                 :string(255)
#  copyright          :string(255)
#  meta               :string(255)
#  size               :integer
#  path               :string(255)
#  unzipped_base_url  :string(255)
#  info               :hstore
#  link               :string(255)
#  default_product_id :integer
#  created_at         :datetime
#  updated_at         :datetime
#

class Asset < ActiveRecord::Base
  self.primary_key = 'id'

  belongs_to :default_product
end

app/models/country.rb
# == Schema Information
#
# Table name: countries
#
#  id         :integer          not null, primary key
#  code       :string(255)
#  name       :string(255)
#  link       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Country < ActiveRecord::Base
end

app/models/default_product.rb
# == Schema Information
#
# Table name: default_products
#
#  id               :string(255)
#  title            :string(255)
#  link             :string(255)
#  qualification_id :integer
#  created_at       :datetime
#  updated_at       :datetime
#

class DefaultProduct < ActiveRecord::Base
  self.primary_key = 'id'

  has_many :assets
  belongs_to :qualification
end

app/models/qualification.rb
# == Schema Information
#
# Table name: qualifications
#
#  id         :string(255)
#  name       :string(255)
#  link       :string(255)
#  country_id :integer
#  created_at :datetime
#  updated_at :datetime
#

class Qualification < ActiveRecord::Base

  self.primary_key = 'id'

  belongs_to :country
  has_many :subjects
  has_one :default_product

  validates_presence_of :id
end

app/models/subject.rb
# == Schema Information
#
# Table name: subjects
#
#  id               :string(255)
#  title            :string(255)
#  link             :string(255)
#  colour           :string(255)
#  qualification_id :integer
#

class Subject < ActiveRecord::Base
  self.primary_key = 'id'

  belongs_to :qualification
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/qualification_controller.rb
class QualificationController < ApplicationController
  def index
    @qualifications = Qualification.all
  end

  def subjects
    @qualification = Qualification.find params[:id]
    @subjects = @qualification.subjects
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/qualification_helper.rb
module QualificationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Gojimo
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = yield

app/views/qualification/index.html.haml
.row
  .col-md-12
    %table.table
      %thead
        %tr
          %th #
          %th name
          %th link
          %th country
          %th
      %tbody
        - @qualifications.each do |qa|
          %tr.qualification
            %th= qa.id
            %td= qa.name
            %td= qa.link
            %td= qa.country.code if not qa.country.nil?
            %td= link_to 'subjects', subjects_path(qa.id)

app/views/qualification/subjects.html.haml
= link_to 'Back', root_path
%h2.text-center= @qualification.name
.row
  .col-md-12
    %table.table
      %thead
        %tr
          %th #
          %th title
          %th link
      %tbody
        - @subjects.each do |su|
          %tr{style: "background-color: #{su.colour  if not su.colour.nil?}"}
            %th= su.id
            %td= su.title
            %td= su.link